### ISSUE TITLE
C extensions not compiled on `poetry install` if module is a dependency

### ISSUE THREAD

**Issue by GasPasChaud** [FirefoxMetzger/mini-extension#3]
Hey there @FirefoxMetzger !

Thanks a lot for you example of how to compile c-extensions when working with `poetry`!

I managed to compile my C-extension locally. By locally I mean while working on the package itself.

Both `poetry build` and `poetry install` are compiling the objects to the desired place.

**However** when I try to use said package as a dependency to another package nothing gets compiled.

I tried with your `shared_library_with_ctypes` that I listed as one of my dependency in my `pyproject..toml`:

```
[tool.poetry.dependencies]
python = "3.10.*"
extension = { git = "git@github.com:FirefoxMetzger/mini-extension.git", subdirectory="shared_library_with_ctypes"}
```

After doing `poetry install` I get the error: `FileNotFoundError` for the `extension/lib` directory.

Am I missing something ? Any help would really be welcome!

Thanks!

**Comment by FirefoxMetzger** [comment]
Glad that you like the project @Jocelyn-Gas 💯 

> However when I try to use said package as a dependency to another package nothing gets compiled.

Interesting approach. I have actually never thought of using poetry in this way. Normally you'd set up a build farm that creates binary wheels for all the platforms you want to support, upload those wheels to pypi (or a private package index), and add a "normal" pip dependency. This way there is no compilation happening on the user's side.

Could you try what happens if you use the `extension_only` example? My hunch is that poetry clones the repo and tries to build the package locally. This will work fine for the other examples, but the ctypes one is special in that the packager doesn't pick up the generated .dll/.so the first time around. The (local) solution is to simply call `poetry build` twice and during the second call the binary is packaged as expected.

(I think this goes back to how poetry virtualized the wheel building environment. I haven't yet managed to figure out how I can control this though, so if you find the correct setting please do share it and I will happily update this example.)

**Comment by GasPasChaud** [comment]
Hi!

That's what I thought, I need to build wheels... 

I tried with the `extension_only` and it works correctly. I'll try if I can use C/Python API in C with my c codebase.

Thanks!

**Comment by FirefoxMetzger** [comment]
> That's what I thought, I need to build wheels...

That depends on your use-case I suppose. If you want to distribute your library, yes. There is no way around building binary wheels, because you can't expect a user to have a working C compiler on their machine.

> I tried with the extension_only and it works correctly. I'll try if I can use C/Python API in C with my c codebase.

This is the more performant option, and if this works in your case I would probably prefer this over ctypes.

**Comment by GasPasChaud** [comment]
> That depends on your use-case I suppose. If you want to distribute your library, yes. There is no way around building binary wheels, because you can't expect a user to have a working C compiler on their machine.

My use case is rather simple, it won't be a public library, it's a private package used at my company, **but** it is a dependency to another of our project -> I need it to be built anywhere it's gonna be installed.


> This is the more performant option, and if this works in your case I would probably prefer this over ctypes.

Do you mean that it's faster to have an extension rather than using `ctypes`? I'm really a beginner in the world of extending Python with C. `ctypes` was the quick and not so dirty solution I found.

My C function takes as input several arrays of doubles and a reference to a struct. (The reference to the struct is the result object in which the c-function need to "write" the results. I'm kinda lost in the docs on how to build such a function in c with the "extension" and not `ctypes`

**Comment by FirefoxMetzger** [comment]
> I need it to be built anywhere it's gonna be installed.

Dependencies are transitive, so if you use a git dependency and have `some_project-(depends)->company_project-(depends)->your_project` then the machine that installs `some_project` will have to clone and compile `your_project` locally as well (its treated like an `sdist`). If you can ensure that pip is able to find a suitable C compiler on any machine that tries to install `some_project` you won't have any issues, otherwise it is better to ship precompiled binary wheels.

> Do you mean that it's faster to have an extension rather than using ctypes?

Yes, a native C extension will typically be faster than `ctypes`. There is also `cffi` which is somewhat of a middle-ground depending on how you use it. If you are willing to work with generated bindings, there is also pybind11 from the C/C++ side, and `boost::python`. All of these do a reasonable job, though I think cffi is probably the easiest to use when coming from python and having little C experience. Otherwise pybind11 tends to be a popular choice.

> My C function takes as input several arrays of doubles and a reference to a struct. (The reference to the struct is the result object in which the c-function need to "write" the results.

This sounds like something you could solve in numpy with the use of [structured arrays](https://numpy.org/doc/stable/user/basics.rec.html), though this ofc depends on the specifics of the application.

> I'm kinda lost in the docs on how to build such a function in c with the "extension" and not ctypes

You could take a look at a recent weekend project of mine:
https://github.com/FirefoxMetzger/pandas_c_extension/blob/bb1f35c3b789969bfcc849334391f7e48d3fc6f5/local/_lib/transforms.c#L14-L37

It's a fairly easy example in the sense that it creates one function which takes an array, does some optimized numerics on the array (not relevant here), and then returns a resulting scalar. Python also has very extensive and good documentation on building C extensions that are worth a read. In particular the introductory examples.

**Comment by GasPasChaud** [comment]
Hello FirefoxMetzger! 

Thanks a lot for your (once again) very detailed answer. I managed to replace `ctypes` with `cffi`. I can now use my c code as I wanted in other projects! You definitely brought me on the right tracks! 

I wish you the best on your projects!
